[package]
name = "gen"
version = "2.0.0"
edition = "2021"
authors = ["Enrique Nieto Matinez <ennimandroid@gmail.com>"]

[lib]
name = "gen"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
chrono = "0.4.38"
